apiVersion: v1
kind: Service
metadata:
  name: {{ include "directus.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8055
      protocol: TCP
      name: http
  selector:
    {{- include "directus.selectorLabels" . | nindent 4 }}
